// frontend/src/lib/components/report/ErrorsView.svelte
<script lang="ts">
	import type { ReportError } from '$lib/types/unified-report';

	import { Panel } from '$lib/components/ui';

	interface Props {
		errors: ReportError[] | undefined;
	}

	const { errors }: Props = $props();

	const list = $derived(errors ?? []);
</script>

<Panel class="shadow-sm" padding="none" rounded="2xl">
	<div class="border-line border-b p-4">
		<h3 class="text-ink text-base leading-none font-semibold tracking-tight">Report Errors</h3>
	</div>
	{#if list.length === 0}
		<div class="text-ink-muted p-6 text-center text-sm">No errors reported.</div>
	{:else}
		<div class="divide-line divide-y">
			{#each list as error, idx (idx)}
				<div class="p-4 text-sm">
					<p class="text-ink font-semibold">{error.message}</p>
					<p class="text-ink-muted mt-1">
						{error.code} · {error.scope}
						{#if error.scannerId}
							· Scanner: {error.scannerId}
						{/if}
						{#if error.pageId}
							· Page: {error.pageId}
						{/if}
					</p>
					<p class="text-ink-muted mt-2 text-xs">
						{error.retryable ? 'Retryable' : 'Not retryable'}
					</p>
				</div>
			{/each}
		</div>
	{/if}
</Panel>

// clients/web/app/components/report/ErrorsView.tsx
import type { ReportError } from '../../lib/types/unified-report';

interface Props {
	errors: ReportError[] | undefined;
	compact?: boolean;
}

export function ErrorsView({ errors, compact = false }: Props) {
	const list = errors ?? [];

	if (list.length === 0 && compact) {
		return (
			<div className="errview errview--compact" data-testid="errors-zero-compact">
				<span className="errview__check" aria-hidden="true">
					✓
				</span>
				<span className="errview__ok-label">No report errors</span>
				<span className="errview__ok-sub">
					All scanners completed without pipeline failures.
				</span>
			</div>
		);
	}

	return (
		<section className="errview__card">
			<header className="errview__head">
				<h3>Report errors</h3>
			</header>
			{list.length === 0 ? (
				<div className="errview__zero">
					<span className="errview__check" aria-hidden="true">
						✓
					</span>
					No errors reported.
				</div>
			) : (
				<ul className="errview__list">
					{list.map((err, idx) => (
						<li key={idx} className="errview__row">
							<p className="errview__msg">{err.message}</p>
							<p className="errview__meta">
								{err.code} · {err.scope}
								{err.scannerId && <> · Scanner: {err.scannerId}</>}
								{err.pageId && <> · Page: {err.pageId}</>}
							</p>
							<p className="errview__retry">
								{err.retryable ? 'Retryable' : 'Not retryable'}
							</p>
						</li>
					))}
				</ul>
			)}
		</section>
	);
}
