// clients/web/src/lib/components/report/IssueFilterSidebar.svelte
<script lang="ts">
	import type { UnifiedReport } from '$lib/types/unified-report';

	import { Input, Select } from '$lib/components/ui';
	import { getSeverityChipClass, getSeverityDotClass } from '$lib/report';
	import { cn } from '$lib/utils';
	import { Search, X } from 'lucide-svelte';

	interface Props {
		report: UnifiedReport;
		activeScanners: string[];
		activeSeverities: string[];
		activePage: string | null;
		activeCategory: string | null;
		searchTerm: string;
		onScannersChange: (next: string[]) => void;
		onSeveritiesChange: (next: string[]) => void;
		onPageChange: (page: string | null) => void;
		onCategoryChange: (category: string | null) => void;
		onSearchChange: (query: string) => void;
		onClearAll: () => void;
		class?: string;
	}

	let {
		report,
		activeScanners,
		activeSeverities,
		activePage,
		activeCategory,
		searchTerm,
		onScannersChange,
		onSeveritiesChange,
		onPageChange,
		onCategoryChange,
		onSearchChange,
		onClearAll,
		class: className
	}: Props = $props();

	const SEVERITIES = ['critical', 'serious', 'moderate', 'minor', 'info'] as const;

	const severityCounts = $derived(
		report.summary.bySeverity ?? {
			critical: 0,
			serious: 0,
			moderate: 0,
			minor: 0,
			info: 0
		}
	);

	const scannerCounts = $derived(report.summary.byScanner ?? {});

	const categories = $derived.by(() => {
		const seen = new Set<string>();
		for (const issue of report.issues) {
			if (issue.category) seen.add(issue.category);
		}
		return Array.from(seen).sort();
	});

	const SEARCH_DEBOUNCE_MS = 250;
	let localSearch = $state('');
	$effect(() => {
		localSearch = searchTerm;
	});

	$effect(() => {
		const value = localSearch;
		if (value === searchTerm) return;
		const timer = setTimeout(() => onSearchChange(value.trim()), SEARCH_DEBOUNCE_MS);
		return () => clearTimeout(timer);
	});

	function toggleScanner(id: string) {
		const next = activeScanners.includes(id)
			? activeScanners.filter((s) => s !== id)
			: [...activeScanners, id];
		onScannersChange(next);
	}

	function toggleSeverity(id: string) {
		const next = activeSeverities.includes(id)
			? activeSeverities.filter((s) => s !== id)
			: [...activeSeverities, id];
		onSeveritiesChange(next);
	}

	const hasActive = $derived(
		activeScanners.length > 0 ||
			activeSeverities.length > 0 ||
			activePage !== null ||
			activeCategory !== null ||
			searchTerm.trim().length > 0
	);
</script>

<aside
	class={cn(
		'border-line bg-surface flex flex-col gap-5 rounded-2xl border p-4 text-sm shadow-sm',
		className
	)}
	aria-label="Issue filters"
	data-testid="issue-filter-sidebar"
>
	<div class="flex items-center justify-between">
		<h3 class="text-ink text-sm font-semibold tracking-tight">Filters</h3>
		{#if hasActive}
			<button
				type="button"
				onclick={onClearAll}
				class="text-accent inline-flex items-center gap-1 text-xs font-semibold hover:underline"
			>
				<X class="h-3 w-3" /> Clear
			</button>
		{/if}
	</div>

	<div>
		<label for="issue-sidebar-search" class="sr-only">Search issues</label>
		<div class="relative">
			<Search class="text-ink-faint absolute top-1/2 left-2.5 h-3.5 w-3.5 -translate-y-1/2" />
			<Input
				id="issue-sidebar-search"
				value={localSearch}
				placeholder="Search issues"
				class="h-9 pl-8 text-xs"
				oninput={(event) => (localSearch = (event.currentTarget as HTMLInputElement).value)}
			/>
		</div>
	</div>

	<fieldset class="flex flex-col gap-1.5">
		<legend class="text-ink-faint mb-1 text-[11px] font-semibold tracking-wide uppercase">
			Scanner
		</legend>
		{#each report.scanners as scanner (scanner.id)}
			{@const count = scannerCounts[scanner.id] ?? 0}
			{@const checked = activeScanners.includes(scanner.id)}
			<label
				class="hover:bg-surface-muted/60 flex cursor-pointer items-center justify-between gap-2 rounded-md px-1.5 py-1"
			>
				<span class="flex items-center gap-2 truncate">
					<input
						type="checkbox"
						{checked}
						onchange={() => toggleScanner(scanner.id)}
						class="border-line text-accent focus:ring-accent h-3.5 w-3.5 rounded"
					/>
					<span class="text-ink truncate text-xs">{scanner.name ?? scanner.id}</span>
				</span>
				<span class="text-ink-faint font-mono text-[11px]">{count.toLocaleString()}</span>
			</label>
		{/each}
	</fieldset>

	<fieldset class="flex flex-col gap-1.5">
		<legend class="text-ink-faint mb-1 text-[11px] font-semibold tracking-wide uppercase">
			Severity
		</legend>
		<div class="flex flex-wrap gap-1.5" data-testid="severity-chip-filters">
			{#each SEVERITIES as severity (severity)}
				{@const count = severityCounts[severity] ?? 0}
				{@const isActive = activeSeverities.includes(severity)}
				<button
					type="button"
					disabled={count === 0}
					aria-pressed={isActive}
					onclick={() => toggleSeverity(severity)}
					class={cn(
						getSeverityChipClass(severity, isActive),
						'gap-1.5',
						count === 0 && 'cursor-not-allowed opacity-40'
					)}
				>
					<span
						class={cn(
							'h-2 w-2 rounded-full',
							isActive ? 'bg-white/80' : getSeverityDotClass(severity)
						)}
					></span>
					{severity}
					<span class="font-mono text-[10px] tabular-nums">{count.toLocaleString()}</span>
				</button>
			{/each}
		</div>
	</fieldset>

	<div class="flex flex-col gap-1.5">
		<label
			for="issue-sidebar-page"
			class="text-ink-faint text-[11px] font-semibold tracking-wide uppercase"
		>
			Page
		</label>
		<Select
			id="issue-sidebar-page"
			uiSize="sm"
			value={activePage ?? 'all'}
			onchange={(event) => {
				const value = (event.currentTarget as HTMLSelectElement).value;
				onPageChange(value === 'all' ? null : value);
			}}
		>
			<option value="all">All pages</option>
			{#each report.pages as page (page.id)}
				<option value={page.id}>{page.path ?? page.url}</option>
			{/each}
		</Select>
	</div>

	{#if categories.length > 0}
		<div class="flex flex-col gap-1.5">
			<label
				for="issue-sidebar-category"
				class="text-ink-faint text-[11px] font-semibold tracking-wide uppercase"
			>
				Category
			</label>
			<Select
				id="issue-sidebar-category"
				uiSize="sm"
				value={activeCategory ?? 'all'}
				onchange={(event) => {
					const value = (event.currentTarget as HTMLSelectElement).value;
					onCategoryChange(value === 'all' ? null : value);
				}}
			>
				<option value="all">All categories</option>
				{#each categories as category (category)}
					<option value={category}>{category}</option>
				{/each}
			</Select>
		</div>
	{/if}
</aside>

// clients/web/app/components/report/IssueFilterSidebar.tsx
import type { PageSummary, ScannerSummary } from '../../lib/types/unified-report';
import {
	SCANNER_META,
	SEVERITY_LEVELS,
	getSeverityChipClass
} from '../../lib/report';

interface Props {
	scanners: ScannerSummary[];
	pages: PageSummary[];
	categories: string[];
	activeScanner: string | null;
	activeSeverity: string | null;
	activePage: string | null;
	activeCategory: string | null;
	searchQuery: string;
	totalCount: number;
	filteredCount: number;
	onScannerChange: (next: string | null) => void;
	onSeverityChange: (next: string | null) => void;
	onPageChange: (next: string | null) => void;
	onCategoryChange: (next: string | null) => void;
	onSearchChange: (next: string) => void;
	onClear: () => void;
}

export function IssueFilterSidebar({
	scanners,
	pages,
	categories,
	activeScanner,
	activeSeverity,
	activePage,
	activeCategory,
	searchQuery,
	totalCount,
	filteredCount,
	onScannerChange,
	onSeverityChange,
	onPageChange,
	onCategoryChange,
	onSearchChange,
	onClear
}: Props) {
	const hasActiveFilters =
		!!activeScanner ||
		!!activeSeverity ||
		!!activePage ||
		!!activeCategory ||
		searchQuery.trim().length > 0;

	return (
		<aside className="iview__panel isidebar" aria-label="Issue filters">
			<div className="isidebar__group">
				<h3>Search</h3>
				<input
					type="search"
					className="isidebar__search"
					placeholder="Title · rule · page…"
					value={searchQuery}
					onChange={(e) => onSearchChange(e.target.value)}
					aria-label="Search issues"
				/>
			</div>

			<div className="isidebar__group" aria-label="Filter by severity">
				<h3>Severity</h3>
				<div className="isidebar__chips">
					<button
						type="button"
						className={`sev-chip${!activeSeverity ? ' active' : ''}`}
						aria-pressed={!activeSeverity}
						onClick={() => onSeverityChange(null)}
					>
						All
					</button>
					{SEVERITY_LEVELS.map((sev) => {
						const isActive = activeSeverity === sev;
						return (
							<button
								key={sev}
								type="button"
								className={getSeverityChipClass(sev, isActive)}
								aria-pressed={isActive}
								onClick={() => onSeverityChange(isActive ? null : sev)}
							>
								{sev}
							</button>
						);
					})}
				</div>
			</div>

			<div className="isidebar__group">
				<h3>Scanner</h3>
				<select
					className="isidebar__select"
					value={activeScanner ?? ''}
					onChange={(e) => onScannerChange(e.target.value || null)}
					aria-label="Filter by scanner"
				>
					<option value="">All scanners</option>
					{scanners.map((scanner) => {
						const label = SCANNER_META[scanner.id]?.label ?? scanner.name ?? scanner.id;
						return (
							<option key={scanner.id} value={scanner.id}>
								{label} ({scanner.issueCount ?? 0})
							</option>
						);
					})}
				</select>
			</div>

			{pages.length > 1 && (
				<div className="isidebar__group">
					<h3>Page</h3>
					<select
						className="isidebar__select"
						value={activePage ?? ''}
						onChange={(e) => onPageChange(e.target.value || null)}
						aria-label="Filter by page"
					>
						<option value="">All pages</option>
						{pages.map((page) => (
							<option key={page.id} value={page.id}>
								{page.path || page.url}
							</option>
						))}
					</select>
				</div>
			)}

			{categories.length > 0 && (
				<div className="isidebar__group">
					<h3>Category</h3>
					<select
						className="isidebar__select"
						value={activeCategory ?? ''}
						onChange={(e) => onCategoryChange(e.target.value || null)}
						aria-label="Filter by category"
					>
						<option value="">All categories</option>
						{categories.map((cat) => (
							<option key={cat} value={cat}>
								{cat}
							</option>
						))}
					</select>
				</div>
			)}

			<div className="isidebar__group" style={{ marginTop: 'auto' }}>
				<p
					style={{
						margin: '0 0 0.6rem',
						fontSize: '0.84rem',
						color: 'var(--ink-muted)'
					}}
				>
					Showing{' '}
					<b style={{ color: 'var(--ink-strong)', fontVariantNumeric: 'tabular-nums' }}>
						{filteredCount}
					</b>{' '}
					of {totalCount}
				</p>
				{hasActiveFilters && (
					<button type="button" className="isidebar__clear" onClick={onClear}>
						Clear filters
					</button>
				)}
			</div>
		</aside>
	);
}
