// frontend/src/lib/components/report/OverviewDashboard.svelte
<script lang="ts">
	import type { UnifiedReport } from '$lib/types/unified-report';

	import { chipVariants, Panel } from '$lib/components/ui';
	import { formatScannerStatus, getScannerStatusTone } from '$lib/report';
	import { cn } from '$lib/utils';
	import { AlertTriangle, CheckCircle2, MinusCircle, XCircle } from 'lucide-svelte';

	import LighthouseSummary from './LighthouseSummary.svelte';
	import SeverityBreakdown from './SeverityBreakdown.svelte';

	interface Props {
		report: UnifiedReport;
		onSelectPage: (pageId: string) => void;
		onSelectScanner: (scannerId: string) => void;
		onSearchIssues: (query: string, scannerId?: string) => void;
	}

	const { report, onSelectPage, onSelectScanner, onSearchIssues }: Props = $props();

	const topPages = $derived(
		[...report.pages].sort((a, b) => b.issueCount - a.issueCount).slice(0, 5)
	);

	const issueDensity = $derived.by(() => {
		if (report.summary.pagesScanned <= 0) return 0;
		return report.summary.totalIssues / report.summary.pagesScanned;
	});

	const affectedRatio = $derived.by(() => {
		if (report.summary.pagesScanned <= 0) return 0;
		return report.summary.pagesWithIssues / report.summary.pagesScanned;
	});

	const criticalRatio = $derived.by(() => {
		if (report.summary.totalIssues <= 0) return 0;
		return (report.summary.bySeverity?.critical ?? 0) / report.summary.totalIssues;
	});

	const highSeverityCount = $derived(
		(report.summary.bySeverity?.critical ?? 0) + (report.summary.bySeverity?.serious ?? 0)
	);

	const riskLabel = $derived.by(() => {
		const critical = report.summary.bySeverity?.critical ?? 0;
		const serious = report.summary.bySeverity?.serious ?? 0;
		// "High risk" only when there are critical issues OR many serious issues
		if (critical > 0 || serious >= 3) return 'High risk';
		if (serious > 0) return 'Elevated risk';
		if (report.summary.totalIssues > 0) return 'Moderate risk';
		return 'Low risk';
	});

	const riskTone = $derived.by(() => {
		if (riskLabel === 'High risk') return 'danger';
		if (riskLabel === 'Elevated risk') return 'warn';
		if (riskLabel === 'Moderate risk') return 'info';
		return 'success';
	});

	const topRules = $derived.by(() => {
		const counts: Record<
			string,
			{ count: number; title: string; scanner: string; ruleId: string }
		> = {};
		for (const issue of report.issues) {
			const key = `${issue.scanner}::${issue.ruleId}`;
			const existing = counts[key];
			if (existing) {
				existing.count += 1;
			} else {
				counts[key] = {
					count: 1,
					title: issue.title ?? issue.ruleId,
					scanner: issue.scanner,
					ruleId: issue.ruleId
				};
			}
		}
		return Object.entries(counts)
			.map(([key, meta]) => ({
				key,
				count: meta.count,
				title: meta.title,
				scanner: meta.scanner,
				ruleId: meta.ruleId
			}))
			.sort((a, b) => b.count - a.count)
			.slice(0, 5);
	});

	const riskSummary = $derived.by(() => {
		const critical = report.summary.bySeverity?.critical ?? 0;
		const serious = report.summary.bySeverity?.serious ?? 0;
		const base = `${report.summary.totalIssues.toLocaleString()} issue${report.summary.totalIssues !== 1 ? 's' : ''} across ${report.summary.pagesScanned.toLocaleString()} page${report.summary.pagesScanned !== 1 ? 's' : ''}.`;
		if (critical > 0 || serious > 0) return `${base} Prioritize critical and serious findings first.`;
		if (report.summary.totalIssues > 0) return `${base} All findings are moderate severity or below.`;
		return 'No issues detected.';
	});

	const issueTone = $derived.by((): 'warn' | 'danger' | null => {
		if (report.summary.totalIssues === 0) return null;
		const critical = report.summary.bySeverity?.critical ?? 0;
		if (critical > 0) return 'danger';
		const serious = report.summary.bySeverity?.serious ?? 0;
		if (serious > 5) return 'warn';
		return null;
	});

	const pagesWithIssuesTone = $derived.by((): 'warn' | 'danger' | null => {
		if (report.summary.pagesScanned === 0) return null;
		const ratio = report.summary.pagesWithIssues / report.summary.pagesScanned;
		if (ratio <= 0.5) return null;
		if (highSeverityCount === 0) return 'warn';
		if (ratio > 0.75) return 'danger';
		if (ratio > 0.5) return 'warn';
		return null;
	});

	const coverageTone = $derived.by((): 'success' | 'warn' | 'danger' => {
		if (affectedRatio <= 0.5) return 'success';
		if (highSeverityCount === 0) return 'warn';
		if (affectedRatio > 0.75) return 'danger';
		return 'warn';
	});

	function getStatusIcon(status: string) {
		switch (status) {
			case 'success':
				return CheckCircle2;
			case 'failed':
				return XCircle;
			case 'skipped':
				return MinusCircle;
			default:
				return AlertTriangle;
		}
	}

	function getRiskChipClass(tone: 'danger' | 'warn' | 'info' | 'success'): string {
		switch (tone) {
			case 'danger':
				return 'border-red-200 bg-red-50 text-red-700';
			case 'warn':
				return 'border-amber-200 bg-amber-50 text-amber-700';
			case 'info':
				return 'border-blue-200 bg-blue-50 text-blue-700';
			default:
				return 'border-emerald-200 bg-emerald-50 text-emerald-700';
		}
	}
</script>

{#snippet summaryCard(title: string, value: number | string, tone?: 'warn' | 'danger' | null)}
	<Panel class="shadow-sm ring-1 ring-line/70" padding="sm" rounded="2xl">
		<div class="flex min-h-24 flex-col justify-between gap-2">
			<p class="text-ink-faint text-xs font-semibold tracking-wide uppercase">{title}</p>
			<p
				class={cn(
					'text-3xl leading-none font-bold',
					tone === 'danger' ? 'text-red-600' : tone === 'warn' ? 'text-amber-600' : 'text-ink'
				)}
			>
				{value}
			</p>
		</div>
	</Panel>
{/snippet}

{#snippet scannerRow(scanner: UnifiedReport['scanners'][number])}
	{@const StatusIcon = getStatusIcon(scanner.status)}
	{@const statusTone = getScannerStatusTone(scanner.status)}
	{@const issueCount = scanner.issueCount ?? report.summary.byScanner?.[scanner.id] ?? 0}
	<button
		onclick={() => onSelectScanner(scanner.id)}
		class="border-line hover:border-accent/50 hover:bg-surface-muted flex w-full items-center justify-between gap-3 rounded-xl border p-3 text-left transition"
	>
		<div class="flex min-w-0 items-start gap-3">
			<StatusIcon
				class={cn(
					'mt-0.5 h-5 w-5',
					scanner.status === 'success'
						? 'text-emerald-500'
						: scanner.status === 'failed'
							? 'text-red-500'
							: scanner.status === 'skipped'
								? 'text-slate-400'
								: 'text-amber-500'
				)}
			/>
			<div class="min-w-0">
				<p class="text-ink truncate font-semibold">
					{scanner.name ?? scanner.id}
				</p>
				<p class="text-ink-muted text-xs">
					{issueCount} issues
				</p>
			</div>
		</div>
		<span class={cn(chipVariants({ tone: statusTone, size: 'xs', caps: true }))}>
			{formatScannerStatus(scanner.status)}
		</span>
	</button>
{/snippet}

<div class="space-y-6">
	<Panel
		class="relative overflow-hidden border border-line/70 bg-gradient-to-br from-surface via-surface to-accent-soft/20 shadow-sm"
		padding="md"
		rounded="2xl"
	>
		<div class="pointer-events-none absolute -top-18 -right-14 h-44 w-44 rounded-full bg-accent/12 blur-3xl"></div>
		<div class="relative flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
			<div>
				<p class="text-ink-faint text-xs font-semibold tracking-[0.12em] uppercase">Risk snapshot</p>
				<div class="mt-2 flex flex-wrap items-center gap-2">
					<p class="text-ink text-2xl font-bold sm:text-3xl">{riskLabel}</p>
					<span
						class={cn(
							'inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-semibold tracking-wide uppercase',
							getRiskChipClass(riskTone)
						)}
					>
						{Math.round(affectedRatio * 100)}% pages impacted
					</span>
				</div>
				<p class="text-ink-muted mt-2 max-w-2xl text-sm">{riskSummary}</p>
			</div>
			<div class="grid grid-cols-3 gap-3 text-right lg:min-w-[380px]">
				<div>
					<p class="text-ink-faint text-[11px] font-semibold tracking-[0.1em] uppercase">Critical share</p>
					<p class="text-ink mt-1 text-2xl font-bold">{Math.round(criticalRatio * 100)}%</p>
				</div>
				<div>
					<p class="text-ink-faint text-[11px] font-semibold tracking-[0.1em] uppercase">Issue density</p>
					<p class="text-ink mt-1 text-2xl font-bold">{issueDensity.toFixed(1)}</p>
				</div>
				<div>
					<p class="text-ink-faint text-[11px] font-semibold tracking-[0.1em] uppercase">Scanners</p>
					<p class="text-ink mt-1 text-2xl font-bold">{report.scanners.length}</p>
				</div>
			</div>
		</div>
	</Panel>

	<div class="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
		{@render summaryCard('Total Issues', report.summary.totalIssues, issueTone)}
		{@render summaryCard('Pages Scanned', report.summary.pagesScanned)}
		{@render summaryCard('Pages With Issues', report.summary.pagesWithIssues, pagesWithIssuesTone)}
		{@render summaryCard('Issue Density', issueDensity.toFixed(1))}
	</div>

	<Panel class="shadow-sm ring-1 ring-line/70" padding="none" rounded="2xl">
		<div class="border-line border-b p-4">
			<h3 class="text-ink text-base leading-none font-semibold tracking-tight">
				Severity Breakdown
			</h3>
		</div>
		<div class="p-4">
			<SeverityBreakdown bySeverity={report.summary.bySeverity} />
		</div>
	</Panel>

	{#if report.summary.lighthouseCategories?.length}
		<Panel class="shadow-sm ring-1 ring-line/70" padding="none" rounded="2xl">
			<div class="border-line border-b p-4">
				<h3 class="text-ink text-base leading-none font-semibold tracking-tight">
					Lighthouse Averages
				</h3>
			</div>
			<div class="p-4">
				<LighthouseSummary categories={report.summary.lighthouseCategories} />
			</div>
		</Panel>
	{/if}

	<div class="grid grid-cols-1 gap-6 lg:grid-cols-[1.2fr,0.8fr]">
		<Panel class="shadow-sm ring-1 ring-line/70 min-w-0" padding="none" rounded="2xl">
			<div class="border-line border-b p-4">
				<h3 class="text-ink text-base leading-none font-semibold tracking-tight">Scanner Status</h3>
			</div>
			<div class="p-4">
				<div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
					{#each report.scanners as scanner (scanner.id)}
						{@render scannerRow(scanner)}
					{/each}
				</div>
			</div>
		</Panel>

		<div class="space-y-4">
			<Panel class="shadow-sm ring-1 ring-line/70" padding="none" rounded="2xl">
				<div class="border-line border-b p-4">
					<h3 class="text-ink text-base leading-none font-semibold tracking-tight">Top Pages</h3>
				</div>
				{#each topPages as page (page.id)}
					<button
						onclick={() => onSelectPage(page.id)}
						class="border-line hover:bg-surface-muted flex w-full items-center justify-between border-b px-4 py-3 text-left text-sm transition last:border-b-0"
					>
						<span class="text-ink truncate font-medium">
							{page.path ?? page.url}
						</span>
						<span class="text-ink-muted text-xs">{page.issueCount} issues</span>
					</button>
				{/each}
			</Panel>

			<Panel class="shadow-sm ring-1 ring-line/70" padding="none" rounded="2xl">
				<div class="border-line border-b p-4">
					<h3 class="text-ink text-base leading-none font-semibold tracking-tight">
						Top Issue Rules
					</h3>
				</div>
				<div class="divide-line divide-y">
					{#each topRules as rule (rule.key)}
						<button
							onclick={() => onSearchIssues(rule.ruleId, rule.scanner)}
							class="hover:bg-surface-muted flex w-full flex-col gap-1 px-4 py-3 text-left text-sm transition"
						>
							<span class="text-ink font-medium">{rule.title}</span>
							<span class="text-ink-muted text-xs">
								{rule.scanner} · {rule.count} occurrences
							</span>
						</button>
					{/each}
				</div>
			</Panel>

			<Panel class="shadow-sm ring-1 ring-line/70" padding="none" rounded="2xl">
				<div class="border-line border-b p-4">
					<h3 class="text-ink text-base leading-none font-semibold tracking-tight">Coverage Heat</h3>
				</div>
				<div class="space-y-3 p-4">
					<div>
						<div class="text-ink-muted mb-1 flex items-center justify-between text-xs">
							<span>Pages with issues</span>
							<span>{Math.round(affectedRatio * 100)}%</span>
						</div>
						<div class="bg-surface-muted h-2 w-full overflow-hidden rounded-full">
							<div
							class={cn(
								'h-full transition-[width] duration-500',
								coverageTone === 'danger'
									? 'bg-red-500'
									: coverageTone === 'warn'
										? 'bg-amber-500'
										: 'bg-emerald-500'
							)}
								style={`width: ${Math.round(affectedRatio * 100)}%`}
							></div>
						</div>
					</div>
					<div>
						<div class="text-ink-muted mb-1 flex items-center justify-between text-xs">
							<span>Critical concentration</span>
							<span>{Math.round(criticalRatio * 100)}%</span>
						</div>
						<div class="bg-surface-muted h-2 w-full overflow-hidden rounded-full">
							<div
								class="h-full bg-red-500 transition-[width] duration-500"
								style={`width: ${Math.round(criticalRatio * 100)}%`}
							></div>
						</div>
					</div>
				</div>
			</Panel>
		</div>
	</div>
</div>

// clients/web/app/components/report/OverviewDashboard.tsx
import { useMemo } from 'react';

import type { UnifiedReport } from '../../lib/types/unified-report';
import {
	formatScannerStatus,
	getScannerStatusTone,
	getSeverityDotClass,
	isManualReviewIssue,
	severityRank
} from '../../lib/report';

import { LighthouseSummary } from './LighthouseSummary';
import { SeverityBreakdown } from './SeverityBreakdown';
import { SeverityDonut } from './SeverityDonut';

interface Props {
	report: UnifiedReport;
	onSelectPage: (pageId: string) => void;
	onSelectScanner: (scannerId: string) => void;
	onSearchIssues: (query: string, scannerId?: string) => void;
	onReviewSeverity?: (severity: string) => void;
}

interface TopRule {
	key: string;
	count: number;
	title: string;
	scanner: string;
	ruleId: string;
	severity: string;
	pageIds: string[];
}

export function OverviewDashboard({
	report,
	onSelectPage,
	onSelectScanner,
	onSearchIssues,
	onReviewSeverity
}: Props) {
	const topPages = useMemo(
		() => [...report.pages].sort((a, b) => b.issueCount - a.issueCount).slice(0, 5),
		[report.pages]
	);

	const distinctIssueCount = useMemo(() => {
		const keys = new Set<string>();
		for (const issue of report.issues) keys.add(`${issue.scanner}::${issue.ruleId}`);
		return keys.size;
	}, [report.issues]);

	const repeatStats = useMemo(() => {
		const counts = new Map<string, number>();
		for (const issue of report.issues) {
			const key = `${issue.scanner}::${issue.ruleId}`;
			counts.set(key, (counts.get(key) ?? 0) + 1);
		}
		let repeats = 0;
		let patterns = 0;
		for (const count of counts.values()) {
			if (count > 1) {
				patterns += 1;
				repeats += count - 1;
			}
		}
		return { repeats, patterns };
	}, [report.issues]);

	const manualCount = useMemo(
		() => report.issues.filter(isManualReviewIssue).length,
		[report.issues]
	);

	const topRules = useMemo<TopRule[]>(() => {
		const counts: Record<
			string,
			{
				count: number;
				title: string;
				scanner: string;
				ruleId: string;
				severity: string;
				pages: Set<string>;
			}
		> = {};
		for (const issue of report.issues) {
			const key = `${issue.scanner}::${issue.ruleId}`;
			const existing = counts[key];
			if (existing) {
				existing.count += 1;
				if (issue.pageId) existing.pages.add(issue.pageId);
				if (severityRank(issue.severity) < severityRank(existing.severity)) {
					existing.severity = issue.severity;
				}
			} else {
				counts[key] = {
					count: 1,
					title: issue.title ?? issue.ruleId,
					scanner: issue.scanner,
					ruleId: issue.ruleId,
					severity: issue.severity,
					pages: new Set(issue.pageId ? [issue.pageId] : [])
				};
			}
		}
		return Object.entries(counts)
			.map(([key, meta]) => ({
				key,
				count: meta.count,
				title: meta.title,
				scanner: meta.scanner,
				ruleId: meta.ruleId,
				severity: meta.severity,
				pageIds: Array.from(meta.pages)
			}))
			.sort((a, b) => {
				const sevDiff = severityRank(a.severity) - severityRank(b.severity);
				if (sevDiff !== 0) return sevDiff;
				return b.count - a.count;
			})
			.slice(0, 5);
	}, [report.issues]);

	const urgent = useMemo(() => {
		const critical = report.summary.bySeverity?.critical ?? 0;
		if (critical > 0) return { severity: 'critical', count: critical };
		const serious = report.summary.bySeverity?.serious ?? 0;
		if (serious > 0) return { severity: 'serious', count: serious };
		return null;
	}, [report.summary.bySeverity]);

	const issueDensity =
		report.summary.pagesScanned > 0
			? report.summary.totalIssues / report.summary.pagesScanned
			: 0;
	const affectedRatio =
		report.summary.pagesScanned > 0
			? report.summary.pagesWithIssues / report.summary.pagesScanned
			: 0;
	const pagesScanned = report.summary.pagesScanned;
	const totalOccurrences = report.summary.totalIssues;
	const hasLighthouse = (report.summary.lighthouseCategories?.length ?? 0) > 0;

	const riskLabel =
		distinctIssueCount === 0
			? 'No issues found'
			: `${distinctIssueCount.toLocaleString()} issue pattern${distinctIssueCount !== 1 ? 's' : ''} found`;

	const riskSummary = (() => {
		if (distinctIssueCount === 0) {
			if ((report.errors?.length ?? 0) > 0) {
				return 'No issues detected, but some scans errored — review before treating this as clean.';
			}
			return 'No issues detected.';
		}
		const occNote =
			totalOccurrences !== distinctIssueCount
				? ` (${totalOccurrences.toLocaleString()} occurrences)`
				: '';
		return `${distinctIssueCount.toLocaleString()} issue pattern${distinctIssueCount !== 1 ? 's' : ''}${occNote} seen across ${report.summary.pagesWithIssues.toLocaleString()} of ${pagesScanned.toLocaleString()} page${pagesScanned !== 1 ? 's' : ''} scanned.`;
	})();

	const pageLabelForId = (pageId: string) => {
		const found = report.pages.find((p) => p.id === pageId);
		return found?.path ?? found?.url ?? pageId;
	};

	return (
		<div className="ovr">
			<section className="ovr__hero">
				<div className="ovr__hero-main">
					<p className="ovr__eyebrow">Overview</p>
					<h2 className="ovr__risk">{riskLabel}</h2>
					<p className="ovr__risk-pill">
						{report.summary.pagesWithIssues.toLocaleString()} of{' '}
						{pagesScanned.toLocaleString()} pages affected
					</p>
					<p className="ovr__summary">{riskSummary}</p>

					{distinctIssueCount > 0 && (
						<div className="ovr__workflow" data-testid="overview-workflow">
							{urgent ? (
								<button
									type="button"
									className="ovr__cta ovr__cta--urgent"
									data-severity={urgent.severity}
									onClick={() =>
										onReviewSeverity
											? onReviewSeverity(urgent.severity)
											: onSearchIssues('')
									}
								>
									Fix {urgent.count.toLocaleString()} {urgent.severity} first →
								</button>
							) : (
								<button
									type="button"
									className="ovr__cta"
									onClick={() => onSearchIssues('')}
								>
									Open issue list →
								</button>
							)}
							{repeatStats.repeats > 0 && (
								<button
									type="button"
									className="ovr__chip-btn"
									onClick={() => onSearchIssues('')}
								>
									<b>{repeatStats.repeats.toLocaleString()}</b> are repeats of{' '}
									<b>{repeatStats.patterns.toLocaleString()}</b> pattern
									{repeatStats.patterns === 1 ? '' : 's'}
								</button>
							)}
							{manualCount > 0 && (
								<button
									type="button"
									className="ovr__chip-btn"
									onClick={() => onSearchIssues('')}
								>
									<b>{manualCount.toLocaleString()}</b> need manual review
								</button>
							)}
							{topPages[0] && (
								<button
									type="button"
									className="ovr__chip-btn"
									onClick={() => onSelectPage(topPages[0]!.id)}
								>
									Inspect most-affected page
								</button>
							)}
						</div>
					)}
				</div>
				<dl className="ovr__hero-stats">
					<div>
						<dt>Pages affected</dt>
						<dd>{report.summary.pagesWithIssues}</dd>
					</div>
					<div>
						<dt>Issue density</dt>
						<dd>{issueDensity.toFixed(1)}</dd>
					</div>
					<div>
						<dt>Scanners</dt>
						<dd>{report.scanners.length}</dd>
					</div>
				</dl>
			</section>

			<div className="ovr__grid">
				<section className="ovr__card ovr__card--wide">
					<header className="ovr__card-head">
						<h3>Severity Mix</h3>
					</header>
					<div className="ovr__mix">
						<SeverityDonut counts={report.summary.bySeverity} centerLabel="issues" />
						<div className="ovr__mix-break">
							<SeverityBreakdown bySeverity={report.summary.bySeverity} />
						</div>
					</div>
					<dl className="ovr__mini-stats">
						<div>
							<dt>Distinct</dt>
							<dd>{distinctIssueCount}</dd>
						</div>
						<div>
							<dt>Occurrences</dt>
							<dd>{totalOccurrences}</dd>
						</div>
						<div>
							<dt>Pages scanned</dt>
							<dd>{pagesScanned}</dd>
						</div>
						<div>
							<dt>Pages w/ issues</dt>
							<dd>{report.summary.pagesWithIssues}</dd>
						</div>
					</dl>
				</section>

				{topRules.length > 0 && (
					<section className="ovr__card ovr__card--wide">
						<header className="ovr__card-head ovr__card-head--split">
							<h3>
								<span className="ovr__fix-tag">FIX</span> Top fixes — start here
							</h3>
							<button
								type="button"
								className="ovr__link-btn"
								onClick={() => onSearchIssues('')}
							>
								Open issue list →
							</button>
						</header>
						<ol className="ovr__fixes" data-testid="top-fixes">
							{topRules.map((fix, idx) => {
								const previewPages = fix.pageIds.slice(0, 2);
								const remainingPages = Math.max(
									0,
									fix.pageIds.length - previewPages.length
								);
								return (
									<li key={fix.key}>
										<button
											type="button"
											className="ovr__fix-row"
											onClick={() => onSearchIssues(fix.ruleId, fix.scanner)}
										>
											<span className="ovr__fix-idx">#{idx + 1}</span>
											<div className="ovr__fix-body">
												<div className="ovr__fix-meta">
													<span className="ovr__fix-sev">
														<span
															className={getSeverityDotClass(fix.severity)}
															aria-hidden="true"
														/>
														{fix.severity}
													</span>
													<span className="ovr__fix-rule">
														{fix.scanner} · {fix.ruleId}
													</span>
												</div>
												<p className="ovr__fix-title">{fix.title}</p>
												<p className="ovr__fix-stats">
													{fix.count.toLocaleString()}{' '}
													{fix.count === 1 ? 'occurrence' : 'occurrences'} ·{' '}
													{fix.pageIds.length}{' '}
													{fix.pageIds.length === 1 ? 'page' : 'pages'}
												</p>
												{previewPages.length > 0 && (
													<span className="ovr__fix-pages">
														{previewPages.map((pid) => (
															<span
																key={pid}
																className="ovr__fix-page"
																title={pageLabelForId(pid)}
															>
																{pageLabelForId(pid)}
															</span>
														))}
														{remainingPages > 0 && (
															<span className="ovr__fix-more">
																+{remainingPages} more
															</span>
														)}
													</span>
												)}
											</div>
											<span className="ovr__fix-arrow" aria-hidden="true">
												→
											</span>
										</button>
									</li>
								);
							})}
						</ol>
					</section>
				)}

				<section
					className={`ovr__card ${hasLighthouse ? 'ovr__card--wide' : 'ovr__card--full'}`}
				>
					<header className="ovr__card-head">
						<h3>Scanner Status</h3>
					</header>
					<div className="ovr__scanners">
						{report.scanners.map((scanner) => {
							const issueCount =
								scanner.issueCount ?? report.summary.byScanner?.[scanner.id] ?? 0;
							const hasError = scanner.status === 'failed' || !!scanner.error;
							const tone = getScannerStatusTone(scanner.status);
							return (
								<div
									key={scanner.id}
									className={`ovr__scanner${hasError ? ' ovr__scanner--err' : ''}`}
								>
									<button
										type="button"
										className="ovr__scanner-btn"
										onClick={() => onSelectScanner(scanner.id)}
									>
										<span className="ovr__scanner-main">
											<span
												className="ovr__scanner-led"
												data-tone={tone}
												aria-hidden="true"
											/>
											<span className="ovr__scanner-meta">
												<span className="ovr__scanner-name">
													{scanner.name ?? scanner.id}
												</span>
												<span className="ovr__scanner-count">
													{issueCount} issue{issueCount === 1 ? '' : 's'}
												</span>
											</span>
										</span>
										<span className="ovr__scanner-status" data-tone={tone}>
											{formatScannerStatus(scanner.status)}
										</span>
									</button>
									{hasError && (
										<div className="ovr__scanner-err-msg">
											<p className="ovr__scanner-err-lab">Scanner failure</p>
											<p>{scanner.error || 'Terminated without producing results.'}</p>
										</div>
									)}
								</div>
							);
						})}
					</div>
				</section>

				{hasLighthouse && (
					<section className="ovr__card ovr__card--wide">
						<header className="ovr__card-head">
							<h3>Lighthouse Averages</h3>
						</header>
						<div className="ovr__card-body">
							<LighthouseSummary
								categories={report.summary.lighthouseCategories ?? []}
							/>
						</div>
					</section>
				)}

				<section className="ovr__card">
					<header className="ovr__card-head">
						<h3>Top Pages</h3>
					</header>
					{topPages.length === 0 ? (
						<div className="ovr__empty">No pages scanned.</div>
					) : (
						topPages.map((page) => (
							<button
								key={page.id}
								type="button"
								className="ovr__page-row"
								onClick={() => onSelectPage(page.id)}
							>
								<span className="ovr__page-label">{page.path ?? page.url}</span>
								<span className="ovr__page-count">
									{page.issueCount} issue{page.issueCount === 1 ? '' : 's'}
								</span>
							</button>
						))
					)}
				</section>

				<section className="ovr__card">
					<header className="ovr__card-head">
						<h3>Patterns to fix</h3>
					</header>
					<div className="ovr__patterns">
						{topRules.map((rule) => (
							<button
								key={rule.key}
								type="button"
								className="ovr__pattern-row"
								onClick={() => onSearchIssues(rule.ruleId, rule.scanner)}
							>
								<span className="ovr__pattern-title">{rule.title}</span>
								<span className="ovr__pattern-meta">
									{rule.scanner} · {rule.count} occurrence
									{rule.count === 1 ? '' : 's'}
								</span>
							</button>
						))}
					</div>
				</section>

				<section className="ovr__card ovr__card--wide">
					<header className="ovr__card-head">
						<h3>Coverage Heat</h3>
					</header>
					<div className="ovr__coverage">
						<div>
							<div className="ovr__coverage-row">
								<span>Pages with issues</span>
								<span>{Math.round(affectedRatio * 100)}%</span>
							</div>
							<div className="ovr__coverage-bar">
								<span
									className="ovr__coverage-fill"
									data-tone={
										affectedRatio > 0.75
											? 'high'
											: affectedRatio > 0.5
												? 'mid'
												: 'low'
									}
									style={{ transform: `scaleX(${affectedRatio})` }}
								/>
							</div>
						</div>
						<div>
							<div className="ovr__coverage-row">
								<span>Distinct issues</span>
								<span>{distinctIssueCount.toLocaleString()}</span>
							</div>
							<p className="ovr__coverage-note">
								{totalOccurrences.toLocaleString()} total occurrence
								{totalOccurrences !== 1 ? 's' : ''} across {report.scanners.length}{' '}
								scanner{report.scanners.length !== 1 ? 's' : ''}.
							</p>
						</div>
					</div>
				</section>
			</div>
		</div>
	);
}
