// frontend/src/lib/components/report/ReportSectionNav.svelte
<script lang="ts">
	import type { UnifiedReport } from '$lib/types/unified-report';

	import { Panel } from '$lib/components/ui';
	import { cn } from '$lib/utils';

	interface Section {
		id: string;
		label: string;
		count?: number;
	}

	interface Props {
		section: string;
		report: UnifiedReport;
		onSectionChange: (sectionId: string) => void;
	}

	const { section, report, onSectionChange }: Props = $props();

	const sections = $derived<Section[]>([
		{ id: 'overview', label: 'Overview' },
		{ id: 'issues', label: 'Issues', count: report.issues.length },
		{ id: 'pages', label: 'Pages', count: report.pages.length },
		{ id: 'scanners', label: 'Scanners', count: report.scanners.length },
		{ id: 'artifacts', label: 'Artifacts' },
		{ id: 'errors', label: 'Errors', count: report.errors?.length ?? 0 }
	]);
</script>

<Panel
	variant="muted"
	padding="xs"
	rounded="2xl"
	class="mb-8 flex flex-wrap gap-2"
	role="tablist"
	aria-label="Report sections"
>
	{#each sections as item (item.id)}
		<button
			onclick={() => onSectionChange(item.id)}
			class={cn(
				'flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold transition',
				section === item.id
					? 'bg-ink text-surface'
					: 'text-ink-muted hover:bg-surface hover:text-ink'
			)}
			role="tab"
			aria-selected={section === item.id}
			aria-controls={`report-panel-${item.id}`}
			id={`report-tab-${item.id}`}
		>
			<span>{item.label}</span>
			{#if typeof item.count === 'number'}
				<span
					class={cn(
						'rounded-full px-2 py-0.5 text-xs font-semibold',
						section === item.id ? 'bg-surface/20 text-surface' : 'bg-surface text-ink-muted'
					)}
					aria-label={`${item.count} ${item.label.toLowerCase()}`}
				>
					{item.count}
				</span>
			{/if}
		</button>
	{/each}
</Panel>

// clients/web/app/components/report/ReportSectionNav.tsx
import type { UnifiedReport } from '../../lib/types/unified-report';

export type ReportSection = 'overview' | 'issues' | 'pages' | 'artifacts';

interface Props {
	report: UnifiedReport;
	section: ReportSection;
	onSectionChange: (next: ReportSection) => void;
}

interface TabSpec {
	id: ReportSection;
	label: string;
	count: number | null;
}

export function ReportSectionNav({ report, section, onSectionChange }: Props) {
	const artifactCount =
		(report.artifacts?.length ?? 0) + (report.errors?.length ?? 0);

	const tabs: TabSpec[] = [
		{ id: 'overview', label: 'Overview', count: null },
		{ id: 'issues', label: 'Issues', count: report.summary.totalIssues ?? 0 },
		{ id: 'pages', label: 'Pages', count: report.summary.pagesScanned ?? 0 },
		{ id: 'artifacts', label: 'Artifacts', count: artifactCount || null }
	];

	return (
		<nav className="rnav" role="tablist" aria-label="Report sections">
			{tabs.map((tab) => {
				const selected = tab.id === section;
				return (
					<button
						key={tab.id}
						type="button"
						role="tab"
						id={`report-tab-${tab.id}`}
						aria-selected={selected}
						aria-controls={`report-panel-${tab.id}`}
						className="rnav__tab"
						onClick={() => onSectionChange(tab.id)}
					>
						<span>{tab.label}</span>
						{tab.count !== null && tab.count > 0 && (
							<span className="rnav__tab-count">{tab.count}</span>
						)}
					</button>
				);
			})}
		</nav>
	);
}
