// clients/web/app/components/report/SeverityDonut.tsx
import type { SeverityCounts } from '../../lib/types/unified-report';
import { SEVERITY_LEVELS } from '../../lib/report';

interface Props {
	counts: SeverityCounts | undefined;
	centerLabel?: string;
	size?: number;
}

const SEV_COLORS: Record<string, string> = {
	critical: 'var(--sev-critical, #dc2626)',
	serious: 'var(--sev-serious, #ea580c)',
	moderate: 'var(--sev-moderate, #d97706)',
	minor: 'var(--sev-minor, #2563eb)',
	info: 'var(--sev-pass, #16a34a)'
};

export function SeverityDonut({ counts, centerLabel = 'issues', size = 132 }: Props) {
	const safe: Record<string, number> = counts ? { ...counts } : {};
	const total = SEVERITY_LEVELS.reduce((sum, k) => sum + (safe[k] ?? 0), 0);
	const radius = size / 2 - 14;
	const circumference = 2 * Math.PI * radius;

	if (total === 0) {
		return (
			<svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} aria-label="No issues">
				<circle
					cx={size / 2}
					cy={size / 2}
					r={radius}
					fill="none"
					stroke="var(--line)"
					strokeWidth={14}
				/>
				<text
					x="50%"
					y="50%"
					textAnchor="middle"
					dominantBaseline="central"
					fill="var(--ink-strong)"
					fontFamily="var(--mono)"
					fontWeight="700"
					fontSize="1.1rem"
				>
					0
				</text>
			</svg>
		);
	}

	let offset = 0;
	const segments = SEVERITY_LEVELS.flatMap((sev) => {
		const value = safe[sev] ?? 0;
		if (value === 0) return [];
		const fraction = value / total;
		const dash = fraction * circumference;
		const segment = (
			<circle
				key={sev}
				cx={size / 2}
				cy={size / 2}
				r={radius}
				fill="none"
				stroke={SEV_COLORS[sev] ?? 'var(--ink-muted)'}
				strokeWidth={14}
				strokeDasharray={`${dash} ${circumference - dash}`}
				strokeDashoffset={-offset}
				transform={`rotate(-90 ${size / 2} ${size / 2})`}
			/>
		);
		offset += dash;
		return [segment];
	});

	return (
		<svg
			width={size}
			height={size}
			viewBox={`0 0 ${size} ${size}`}
			aria-label={`${total} ${centerLabel}`}
		>
			<circle
				cx={size / 2}
				cy={size / 2}
				r={radius}
				fill="none"
				stroke="var(--line)"
				strokeWidth={14}
			/>
			{segments}
			<text
				x="50%"
				y="46%"
				textAnchor="middle"
				dominantBaseline="central"
				fill="var(--ink-strong)"
				fontFamily="var(--mono)"
				fontWeight="700"
				fontSize="1.35rem"
			>
				{total.toLocaleString()}
			</text>
			<text
				x="50%"
				y="62%"
				textAnchor="middle"
				dominantBaseline="central"
				fill="var(--ink-faint)"
				fontFamily="var(--mono)"
				fontSize="0.66rem"
				letterSpacing="0.08em"
				style={{ textTransform: 'uppercase' }}
			>
				{centerLabel}
			</text>
		</svg>
	);
}

// clients/web/src/lib/components/report/SeverityDonut.svelte
<script lang="ts">
	import type { SeverityCounts } from '$lib/types/unified-report';

	import { SEVERITY_LEVELS, getSeverityStrokeColor } from '$lib/report';
	import { cn } from '$lib/utils';

	interface Props {
		counts: Partial<SeverityCounts> | null | undefined;
		/** Number shown in the donut center; defaults to the sum of all counts. */
		centerValue?: number | null;
		centerLabel?: string;
		/** Rendered size in px (the SVG scales from an 80×80 viewBox). */
		size?: number;
		class?: string;
	}

	let {
		counts,
		centerValue = null,
		centerLabel = 'issues',
		size = 112,
		class: className
	}: Props = $props();

	const RADIUS = 30;
	const STROKE = 9;
	const CIRCUMFERENCE = 2 * Math.PI * RADIUS;
	// Visual gap between adjacent segments, in circumference units.
	const SEGMENT_GAP = 1.5;

	const total = $derived(SEVERITY_LEVELS.reduce((sum, level) => sum + (counts?.[level] ?? 0), 0));
	const displayValue = $derived(centerValue ?? total);

	const segments = $derived.by(() => {
		if (total === 0) return [];
		const nonZero = SEVERITY_LEVELS.filter((level) => (counts?.[level] ?? 0) > 0);
		const gap = nonZero.length > 1 ? SEGMENT_GAP : 0;
		let offset = 0;
		return nonZero.map((level) => {
			const count = counts?.[level] ?? 0;
			const arc = (count / total) * CIRCUMFERENCE;
			const segment = {
				level,
				count,
				length: Math.max(arc - gap, 0.5),
				offset
			};
			offset += arc;
			return segment;
		});
	});
</script>

<div
	class={cn('relative inline-flex shrink-0 items-center justify-center', className)}
	data-testid="severity-donut"
	role="img"
	aria-label="Severity distribution: {SEVERITY_LEVELS.map(
		(level) => `${counts?.[level] ?? 0} ${level}`
	).join(', ')}"
>
	<svg viewBox="0 0 80 80" width={size} height={size} class="-rotate-90" aria-hidden="true">
		<circle cx="40" cy="40" r={RADIUS} fill="none" class="stroke-surface-muted" stroke-width={STROKE} />
		{#each segments as segment, idx (segment.level)}
			<circle
				cx="40"
				cy="40"
				r={RADIUS}
				fill="none"
				stroke={getSeverityStrokeColor(segment.level)}
				stroke-width={STROKE}
				stroke-linecap={segments.length > 1 ? 'butt' : 'round'}
				class="animate-donut-segment"
				stroke-dasharray={`${segment.length} ${CIRCUMFERENCE - segment.length}`}
				style={`stroke-dashoffset: ${-segment.offset}; --segment-length: ${segment.length}; --segment-gap: ${CIRCUMFERENCE - segment.length}; animation-delay: ${idx * 120}ms;`}
			/>
		{/each}
	</svg>
	<div class="pointer-events-none absolute inset-0 flex flex-col items-center justify-center">
		<span class="text-ink-strong font-mono text-2xl leading-none font-bold tabular-nums">
			{displayValue.toLocaleString()}
		</span>
		{#if centerLabel}
			<span class="text-ink-faint mt-0.5 text-[9px] font-semibold tracking-wider uppercase">
				{centerLabel}
			</span>
		{/if}
	</div>
</div>
